/*
 * Mittwald API
 *
 * ## Introduction  This OpenAPI spec documents the mittwald API. It follows the [OpenAPI 3.0.0 specification](https://spec.openapis.org/oas/v3.0.0.html).  ## Authentication  You will need an API token to access the API. You can obtain one by logging into the [mStudio](https://studio.mittwald.de) and navigating to the [\"API Tokens\" section in the user menu](https://studio.mittwald.de/app/profile/api-tokens).  When making requests to the API, you can authenticate by passing your API token in the `X-Access-Token` header or as a bearer token.  ## Rate Limiting  Please note that usage of the API is rate-limited to prevent abuse. You can inspect the rate limiting for your current user by observing the `X-Ratelimit-*` headers included in each response.  ## mStudio  A main consumer of the mittwald API is the management interface for our customers, the [mStudio](https://studio.mittwald.de).  ## Contact and support  For support, please use the [mStudio support area](https://studio.mittwald.de/app/support/conversations) or drop us an email at [support@mittwald.de](mailto:support@mittwald.de).  For security issues, please report to [security@mittwald.de](mailto:security@mittwald.de). 
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeMittwaldV1SslCertificateErrorMessage {
    /// Failed to read the certificate.
    String(String),
    /// Failed to decode the certificate.
    String(String),
    /// An error occurred while parsing the certificate.
    String(String),
    /// The certificate is self-signed.
    String(String),
    /// The certificate is not authorized to sign.
    String(String),
    /// The certificate has expired.
    String(String),
    /// The Certificate Authority (CA) is not authorized for this name.
    String(String),
    /// There are too many intermediate certificates.
    String(String),
    /// The certificate's usage is incompatible.
    String(String),
    /// The certificate is signed by an unknown authority.
    String(String),
    /// Failed to read the private key.
    String(String),
    /// Failed to decode the private key.
    String(String),
    /// An error occurred while parsing the private key.
    String(String),
    /// The private key is encrypted.
    String(String),
    /// The private key is not RSA.
    String(String),
    /// The private key does not match the certificate.
    String(String),
    /// An unknown error occurred related to Cloudflare.
    String(String),
    /// An unknown error occurred.
    String(String),
}

impl Default for DeMittwaldV1SslCertificateErrorMessage {
    fn default() -> Self {
        Self::String(Default::default())
    }
}

