/*
 * Mittwald API
 *
 * ## Introduction  This OpenAPI spec documents the mittwald API. It follows the [OpenAPI 3.0.0 specification](https://spec.openapis.org/oas/v3.0.0.html).  ## Authentication  You will need an API token to access the API. You can obtain one by logging into the [mStudio](https://studio.mittwald.de) and navigating to the [\"API Tokens\" section in the user menu](https://studio.mittwald.de/app/profile/api-tokens).  When making requests to the API, you can authenticate by passing your API token in the `X-Access-Token` header or as a bearer token.  ## Rate Limiting  Please note that usage of the API is rate-limited to prevent abuse. You can inspect the rate limiting for your current user by observing the `X-Ratelimit-*` headers included in each response.  ## mStudio  A main consumer of the mittwald API is the management interface for our customers, the [mStudio](https://studio.mittwald.de).  ## Contact and support  For support, please use the [mStudio support area](https://studio.mittwald.de/app/support/conversations) or drop us an email at [support@mittwald.de](mailto:support@mittwald.de).  For security issues, please report to [security@mittwald.de](mailto:security@mittwald.de). 
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DePeriodMittwaldPeriodV1PeriodConversationPeriodMessage {
    #[serde(rename = "conversationId")]
    pub conversation_id: uuid::Uuid,
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(rename = "createdBy", skip_serializing_if = "Option::is_none")]
    pub created_by: Option<Box<models::DePeriodMittwaldPeriodV1PeriodConversationPeriodUser>>,
    #[serde(rename = "files", skip_serializing_if = "Option::is_none")]
    pub files: Option<Vec<models::DePeriodMittwaldPeriodV1PeriodConversationPeriodFile>>,
    #[serde(rename = "internal", skip_serializing_if = "Option::is_none")]
    pub internal: Option<bool>,
    #[serde(rename = "messageContent", skip_serializing_if = "Option::is_none")]
    pub message_content: Option<String>,
    #[serde(rename = "messageId")]
    pub message_id: uuid::Uuid,
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl DePeriodMittwaldPeriodV1PeriodConversationPeriodMessage {
    pub fn new(conversation_id: uuid::Uuid, created_at: String, message_id: uuid::Uuid, r#type: Type) -> DePeriodMittwaldPeriodV1PeriodConversationPeriodMessage {
        DePeriodMittwaldPeriodV1PeriodConversationPeriodMessage {
            conversation_id,
            created_at,
            created_by: None,
            files: None,
            internal: None,
            message_content: None,
            message_id,
            r#type,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "MESSAGE")]
    Message,
}

impl Default for Type {
    fn default() -> Type {
        Self::Message
    }
}

