/*
 * Mittwald API
 *
 * ## Introduction  This OpenAPI spec documents the mittwald API. It follows the [OpenAPI 3.0.0 specification](https://spec.openapis.org/oas/v3.0.0.html).  ## Authentication  You will need an API token to access the API. You can obtain one by logging into the [mStudio](https://studio.mittwald.de) and navigating to the [\"API Tokens\" section in the user menu](https://studio.mittwald.de/app/profile/api-tokens).  When making requests to the API, you can authenticate by passing your API token in the `X-Access-Token` header or as a bearer token.  ## Rate Limiting  Please note that usage of the API is rate-limited to prevent abuse. You can inspect the rate limiting for your current user by observing the `X-Ratelimit-*` headers included in each response.  ## mStudio  A main consumer of the mittwald API is the management interface for our customers, the [mStudio](https://studio.mittwald.de).  ## Contact and support  For support, please use the [mStudio support area](https://studio.mittwald.de/app/support/conversations) or drop us an email at [support@mittwald.de](mailto:support@mittwald.de).  For security issues, please report to [security@mittwald.de](mailto:security@mittwald.de). 
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DePeriodMittwaldPeriodV1PeriodArticlePeriodArticleAttributes {
    #[serde(rename = "customerEditable", skip_serializing_if = "Option::is_none")]
    pub customer_editable: Option<bool>,
    #[serde(rename = "key")]
    pub key: String,
    #[serde(rename = "mergeType", skip_serializing_if = "Option::is_none")]
    pub merge_type: Option<MergeType>,
    #[serde(rename = "readonly", skip_serializing_if = "Option::is_none")]
    pub readonly: Option<bool>,
    #[serde(rename = "required", skip_serializing_if = "Option::is_none")]
    pub required: Option<bool>,
    #[serde(rename = "unit", skip_serializing_if = "Option::is_none")]
    pub unit: Option<String>,
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<String>,
}

impl DePeriodMittwaldPeriodV1PeriodArticlePeriodArticleAttributes {
    pub fn new(key: String) -> DePeriodMittwaldPeriodV1PeriodArticlePeriodArticleAttributes {
        DePeriodMittwaldPeriodV1PeriodArticlePeriodArticleAttributes {
            customer_editable: None,
            key,
            merge_type: None,
            readonly: None,
            required: None,
            unit: None,
            value: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum MergeType {
    #[serde(rename = "add")]
    Add,
    #[serde(rename = "set")]
    Set,
}

impl Default for MergeType {
    fn default() -> MergeType {
        Self::Add
    }
}

