/*
 * Mittwald API
 *
 * ## Introduction  This OpenAPI spec documents the mittwald API. It follows the [OpenAPI 3.0.0 specification](https://spec.openapis.org/oas/v3.0.0.html).  ## Authentication  You will need an API token to access the API. You can obtain one by logging into the [mStudio](https://studio.mittwald.de) and navigating to the [\"API Tokens\" section in the user menu](https://studio.mittwald.de/app/profile/api-tokens).  When making requests to the API, you can authenticate by passing your API token in the `X-Access-Token` header or as a bearer token.  ## Rate Limiting  Please note that usage of the API is rate-limited to prevent abuse. You can inspect the rate limiting for your current user by observing the `X-Ratelimit-*` headers included in each response.  ## mStudio  A main consumer of the mittwald API is the management interface for our customers, the [mStudio](https://studio.mittwald.de).  ## Contact and support  For support, please use the [mStudio support area](https://studio.mittwald.de/app/support/conversations) or drop us an email at [support@mittwald.de](mailto:support@mittwald.de).  For security issues, please report to [security@mittwald.de](mailto:security@mittwald.de). 
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DePeriodMittwaldPeriodV1PeriodInvoicePeriodPaymentSettingsDebit {
    #[serde(rename = "accountHolder")]
    pub account_holder: String,
    /// Optional. Required for payments outside of the European Union.
    #[serde(rename = "bic", skip_serializing_if = "Option::is_none")]
    pub bic: Option<String>,
    #[serde(rename = "iban")]
    pub iban: String,
    #[serde(rename = "method")]
    pub method: Method,
}

impl DePeriodMittwaldPeriodV1PeriodInvoicePeriodPaymentSettingsDebit {
    pub fn new(account_holder: String, iban: String, method: Method) -> DePeriodMittwaldPeriodV1PeriodInvoicePeriodPaymentSettingsDebit {
        DePeriodMittwaldPeriodV1PeriodInvoicePeriodPaymentSettingsDebit {
            account_holder,
            bic: None,
            iban,
            method,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Method {
    #[serde(rename = "debit")]
    Debit,
}

impl Default for Method {
    fn default() -> Method {
        Self::Debit
    }
}

