/*
 * Mittwald API
 *
 * ## Introduction  This OpenAPI spec documents the mittwald API. It follows the [OpenAPI 3.0.0 specification](https://spec.openapis.org/oas/v3.0.0.html).  ## Authentication  You will need an API token to access the API. You can obtain one by logging into the [mStudio](https://studio.mittwald.de) and navigating to the [\"API Tokens\" section in the user menu](https://studio.mittwald.de/app/profile/api-tokens).  When making requests to the API, you can authenticate by passing your API token in the `X-Access-Token` header or as a bearer token.  ## Rate Limiting  Please note that usage of the API is rate-limited to prevent abuse. You can inspect the rate limiting for your current user by observing the `X-Ratelimit-*` headers included in each response.  ## mStudio  A main consumer of the mittwald API is the management interface for our customers, the [mStudio](https://studio.mittwald.de).  ## Contact and support  For support, please use the [mStudio support area](https://studio.mittwald.de/app/support/conversations) or drop us an email at [support@mittwald.de](mailto:support@mittwald.de).  For security issues, please report to [security@mittwald.de](mailto:security@mittwald.de). 
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DePeriodMittwaldPeriodV1PeriodAppPeriodAppInstallation : An AppInstallation is a concrete manifestation of an App in a specific AppVersion.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DePeriodMittwaldPeriodV1PeriodAppPeriodAppInstallation {
    #[serde(rename = "appId")]
    pub app_id: uuid::Uuid,
    #[serde(rename = "appVersion")]
    pub app_version: Box<models::DePeriodMittwaldPeriodV1PeriodAppPeriodVersionStatus>,
    #[serde(rename = "customDocumentRoot", skip_serializing_if = "Option::is_none")]
    pub custom_document_root: Option<String>,
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "disabled")]
    pub disabled: bool,
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "installationPath")]
    pub installation_path: String,
    #[serde(rename = "linkedDatabases", skip_serializing_if = "Option::is_none")]
    pub linked_databases: Option<Vec<models::DePeriodMittwaldPeriodV1PeriodAppPeriodLinkedDatabase>>,
    #[serde(rename = "processes", skip_serializing_if = "Option::is_none")]
    pub processes: Option<Vec<uuid::Uuid>>,
    #[serde(rename = "projectId", skip_serializing_if = "Option::is_none")]
    pub project_id: Option<uuid::Uuid>,
    #[serde(rename = "screenshotId", skip_serializing_if = "Option::is_none")]
    pub screenshot_id: Option<uuid::Uuid>,
    #[serde(rename = "screenshotRef", skip_serializing_if = "Option::is_none")]
    pub screenshot_ref: Option<String>,
    #[serde(rename = "shortId")]
    pub short_id: String,
    #[serde(rename = "systemSoftware", skip_serializing_if = "Option::is_none")]
    pub system_software: Option<Vec<models::DePeriodMittwaldPeriodV1PeriodAppPeriodInstalledSystemSoftware>>,
    #[serde(rename = "updatePolicy", skip_serializing_if = "Option::is_none")]
    pub update_policy: Option<models::DePeriodMittwaldPeriodV1PeriodAppPeriodAppUpdatePolicy>,
    #[serde(rename = "userInputs", skip_serializing_if = "Option::is_none")]
    pub user_inputs: Option<Vec<models::DePeriodMittwaldPeriodV1PeriodAppPeriodSavedUserInput>>,
}

impl DePeriodMittwaldPeriodV1PeriodAppPeriodAppInstallation {
    /// An AppInstallation is a concrete manifestation of an App in a specific AppVersion.
    pub fn new(app_id: uuid::Uuid, app_version: models::DePeriodMittwaldPeriodV1PeriodAppPeriodVersionStatus, description: String, disabled: bool, id: uuid::Uuid, installation_path: String, short_id: String) -> DePeriodMittwaldPeriodV1PeriodAppPeriodAppInstallation {
        DePeriodMittwaldPeriodV1PeriodAppPeriodAppInstallation {
            app_id,
            app_version: Box::new(app_version),
            custom_document_root: None,
            description,
            disabled,
            id,
            installation_path,
            linked_databases: None,
            processes: None,
            project_id: None,
            screenshot_id: None,
            screenshot_ref: None,
            short_id,
            system_software: None,
            update_policy: None,
            user_inputs: None,
        }
    }
}

