/*
 * Mittwald API
 *
 * ## Introduction  This OpenAPI spec documents the mittwald API. It follows the [OpenAPI 3.0.0 specification](https://spec.openapis.org/oas/v3.0.0.html).  ## Authentication  You will need an API token to access the API. You can obtain one by logging into the [mStudio](https://studio.mittwald.de) and navigating to the [\"API Tokens\" section in the user menu](https://studio.mittwald.de/app/profile/api-tokens).  When making requests to the API, you can authenticate by passing your API token in the `X-Access-Token` header or as a bearer token.  ## Rate Limiting  Please note that usage of the API is rate-limited to prevent abuse. You can inspect the rate limiting for your current user by observing the `X-Ratelimit-*` headers included in each response.  ## mStudio  A main consumer of the mittwald API is the management interface for our customers, the [mStudio](https://studio.mittwald.de).  ## Contact and support  For support, please use the [mStudio support area](https://studio.mittwald.de/app/support/conversations) or drop us an email at [support@mittwald.de](mailto:support@mittwald.de).  For security issues, please report to [security@mittwald.de](mailto:security@mittwald.de). 
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DePeriodMittwaldPeriodV1PeriodAppPeriodInstalledSystemSoftware : InstalledSystemSoftware describes the currently configured and installed SystemSoftwareVersion of a SystemSoftware besides the desired SystemSoftwareUpdatePolicy inside an AppInstallation.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DePeriodMittwaldPeriodV1PeriodAppPeriodInstalledSystemSoftware {
    #[serde(rename = "systemSoftwareId")]
    pub system_software_id: uuid::Uuid,
    #[serde(rename = "systemSoftwareVersion")]
    pub system_software_version: Box<models::DePeriodMittwaldPeriodV1PeriodAppPeriodVersionStatus>,
    #[serde(rename = "updatePolicy")]
    pub update_policy: models::DePeriodMittwaldPeriodV1PeriodAppPeriodSystemSoftwareUpdatePolicy,
}

impl DePeriodMittwaldPeriodV1PeriodAppPeriodInstalledSystemSoftware {
    /// InstalledSystemSoftware describes the currently configured and installed SystemSoftwareVersion of a SystemSoftware besides the desired SystemSoftwareUpdatePolicy inside an AppInstallation.
    pub fn new(system_software_id: uuid::Uuid, system_software_version: models::DePeriodMittwaldPeriodV1PeriodAppPeriodVersionStatus, update_policy: models::DePeriodMittwaldPeriodV1PeriodAppPeriodSystemSoftwareUpdatePolicy) -> DePeriodMittwaldPeriodV1PeriodAppPeriodInstalledSystemSoftware {
        DePeriodMittwaldPeriodV1PeriodAppPeriodInstalledSystemSoftware {
            system_software_id,
            system_software_version: Box::new(system_software_version),
            update_policy,
        }
    }
}

