/*
 * Mittwald API
 *
 * ## Introduction  This OpenAPI spec documents the mittwald API. It follows the [OpenAPI 3.0.0 specification](https://spec.openapis.org/oas/v3.0.0.html).  ## Authentication  You will need an API token to access the API. You can obtain one by logging into the [mStudio](https://studio.mittwald.de) and navigating to the [\"API Tokens\" section in the user menu](https://studio.mittwald.de/app/profile/api-tokens).  When making requests to the API, you can authenticate by passing your API token in the `X-Access-Token` header or as a bearer token.  ## Rate Limiting  Please note that usage of the API is rate-limited to prevent abuse. You can inspect the rate limiting for your current user by observing the `X-Ratelimit-*` headers included in each response.  ## mStudio  A main consumer of the mittwald API is the management interface for our customers, the [mStudio](https://studio.mittwald.de).  ## Contact and support  For support, please use the [mStudio support area](https://studio.mittwald.de/app/support/conversations) or drop us an email at [support@mittwald.de](mailto:support@mittwald.de).  For security issues, please report to [security@mittwald.de](mailto:security@mittwald.de). 
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DePeriodMittwaldPeriodV1PeriodAppPeriodUserInputFormat : UserInputFormat is an enum, describing the possible data formats of a UserInput, the given values can be validated against.
/// UserInputFormat is an enum, describing the possible data formats of a UserInput, the given values can be validated against.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DePeriodMittwaldPeriodV1PeriodAppPeriodUserInputFormat {
    #[serde(rename = "email")]
    Email,
    #[serde(rename = "password")]
    Password,
    #[serde(rename = "url")]
    Url,
    #[serde(rename = "uri")]
    Uri,

}

impl std::fmt::Display for DePeriodMittwaldPeriodV1PeriodAppPeriodUserInputFormat {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Email => write!(f, "email"),
            Self::Password => write!(f, "password"),
            Self::Url => write!(f, "url"),
            Self::Uri => write!(f, "uri"),
        }
    }
}

impl Default for DePeriodMittwaldPeriodV1PeriodAppPeriodUserInputFormat {
    fn default() -> DePeriodMittwaldPeriodV1PeriodAppPeriodUserInputFormat {
        Self::Email
    }
}

