/*
 * Mittwald API
 *
 * ## Introduction  This OpenAPI spec documents the mittwald API. It follows the [OpenAPI 3.0.0 specification](https://spec.openapis.org/oas/v3.0.0.html).  ## Authentication  You will need an API token to access the API. You can obtain one by logging into the [mStudio](https://studio.mittwald.de) and navigating to the [\"API Tokens\" section in the user menu](https://studio.mittwald.de/app/profile/api-tokens).  When making requests to the API, you can authenticate by passing your API token in the `X-Access-Token` header or as a bearer token.  ## Rate Limiting  Please note that usage of the API is rate-limited to prevent abuse. You can inspect the rate limiting for your current user by observing the `X-Ratelimit-*` headers included in each response.  ## mStudio  A main consumer of the mittwald API is the management interface for our customers, the [mStudio](https://studio.mittwald.de).  ## Contact and support  For support, please use the [mStudio support area](https://studio.mittwald.de/app/support/conversations) or drop us an email at [support@mittwald.de](mailto:support@mittwald.de).  For security issues, please report to [security@mittwald.de](mailto:security@mittwald.de). 
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DePeriodMittwaldPeriodV1PeriodBackupPeriodProjectBackupSchedule {
    #[serde(rename = "createdAt", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    /// Description of this ProjectBackupSchedule.
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// ID of this ProjectBackupSchedule.
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    /// True if this ProjectBackupSchedule was created and is managed by mittwald.
    #[serde(rename = "isSystemBackup")]
    pub is_system_backup: bool,
    /// ID of the Project this ProjectBackupSchedule belongs to.
    #[serde(rename = "projectId")]
    pub project_id: uuid::Uuid,
    /// Execution schedule in crontab notation.
    #[serde(rename = "schedule")]
    pub schedule: String,
    /// TTL of the ProjectBackupSchedule as time string.
    #[serde(rename = "ttl", skip_serializing_if = "Option::is_none")]
    pub ttl: Option<String>,
    #[serde(rename = "updatedAt", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<String>,
}

impl DePeriodMittwaldPeriodV1PeriodBackupPeriodProjectBackupSchedule {
    pub fn new(id: uuid::Uuid, is_system_backup: bool, project_id: uuid::Uuid, schedule: String) -> DePeriodMittwaldPeriodV1PeriodBackupPeriodProjectBackupSchedule {
        DePeriodMittwaldPeriodV1PeriodBackupPeriodProjectBackupSchedule {
            created_at: None,
            description: None,
            id,
            is_system_backup,
            project_id,
            schedule,
            ttl: None,
            updated_at: None,
        }
    }
}

